baseURL = "http://placedata.net/"
languageCode = "en-us"
title = "Location Intelligence"
theme="ezhil"


copyright = "© 2020-2021 Carlo Bailey"

# Number of characters to show in summary.
summaryLength = 0

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Exploring the use of machine learning and advanced analytics for geospatial and urban applications"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    mode = "auto"

    customCSS = "css/custom.css"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/about"
weight = 2

[[menu.main]]
name = "Tutorials"
url = "/posts"
weight = 3

[[menu.main]]
name = "Resources"
url = "/resources"
weight = 4

[[menu.main]]
name = "Assignments"
url = "/assignments"
weight = 5


# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/carlobailey"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/carlo-bailey/"
